[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v -s
markers =
    smoke: smoke tests
    case_50556: test case 50556
    case_50557: test case 50557
    case_53609: test case 53609
    case_53610: test case 53610
